#############################################
# General
#############################################
home_dir: "~"

##############################################
# Homebrew
##############################################
homebrew_installed_packages:
  - git
  - gh
  - httpie
  - ssh-copy-id
  - openssl
  - wget
  - thefuck
  - kubernetes-cli
  - tmux
  - sketchybar
  - lazygit
  - ripgrep
  - fzf
  - bat
  - fd
  - fish
  - starship
  - zoxide
  - fzf
  - nodenv

homebrew_taps:
  - nikitabobko/tap
  - FelixKratz/formulae

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - ghostty
  - google-chrome
  - slack
  - jetbrains-toolbox
  - raycast
  - obsidian
  - insomnia
  - font-jetbrains-mono-nerd-font
  - font-fira-code-nerd-font
  - aerospace

homebrew_cask_accept_external_apps: true

##############################################
# Dotfiles
##############################################
dotfiles_home: "{{home_dir}}"
dotfiles_files:
  - .zshrc
  - .gitignore
  - .ideavimrc
  - .config/nvim
  - .config/sketchybar
  - .config/aerospace/aerospace.toml
  - .config/ghostty/config
  - .config/fish/config.fish
  - .tmux.conf

##############################################
# oh-my-fish
##############################################
omf_plugins:
  - "nodenv"
  - "https://github.com/catppuccin/fish"

fisher_plugins:
  - "jethrokuan/fzf"

##############################################
# git-repos
##############################################
git_repos_to_clone:
  - repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{home_dir}}/.tmux/plugins/tpm"
    version: master
  - repo: "https://github.com/catppuccin/alacritty"
    dest: "{{home_dir}}/.config/alacritty/catppuccin"
    version: main
  - repo: "git@github.com:lordthorzonus/ble2mqtt-gateway"
    dest: "{{home_dir}}/projects/personal/ble2mqtt-gateway"
    version: main
  - repo: "git@github.com:lordthorzonus/homelab-provisioning"
    dest: "{{home_dir}}/projects/personal/homelab-provisioning"
    version: main
  - repo: "git@github.com:lordthorzonus/oura-api-exporter"
    dest: "{{home_dir}}/projects/personal/oura-api-exporter"
    version: main
  - repo: "git@github.com:lordthorzonus/php-dataloader"
    dest: "{{home_dir}}/projects/personal/php-dataloader"
    version: master
git_project_base_folders:
  - "{{home_dir}}/projects"
  - "{{home_dir}}/projects/personal"
  - "{{home_dir}}/projects/work"
