#############################################
# General
#############################################
home_dir: "~"

##############################################
# Homebrew
##############################################
homebrew_installed_packages:
  - git
  - gh
  - httpie
  - ssh-copy-id
  - openssl
  - wget
  - thefuck
  - kubernetes-cli
  - zsh
  - tmux
  - sketchybar
  - lazygit
  - ripgrep
  - fzf
  - bat
  - fd

homebrew_taps:
  - nikitabobko/tap
  - FelixKratz/formulae

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - google-chrome
  - slack
  - iterm2
  - jetbrains-toolbox
  - raycast
  - obsidian
  - insomnia
  - font-jetbrains-mono-nerd-font
  - font-fira-code-nerd-font
  - wezterm
  - aerospace

homebrew_cask_accept_external_apps: true

##############################################
# Dotfiles
##############################################
dotfiles_home: "{{home_dir}}"
dotfiles_files:
  - .zshrc
  - .gitignore
  - .ideavimrc
  - .config/nvim
  - .config/sketchybar
  - .config/aerospace/aerospace.toml
  - .config/alacritty/alacritty.toml
  - .tmux.conf
  - .wezterm.lua

##############################################
# oh-my-zsh
##############################################
omz_home: "{{home_dir}}/.oh-my-zsh"
omz_themes:
  - name: spaceship
    git_repo: "https://github.com/spaceship-prompt/spaceship-prompt.git"
omz_plugins:
  - name: zsh-syntax-highlighting
    git_repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  - name: zsh-autosuggestions
    git_repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
  - name: zsh-completions
    git_repo: "https://github.com/zsh-users/zsh-completions.git"
  - name: zsh-vi-mode
    git_repo: "https://github.com/jeffreytse/zsh-vi-mode"

##############################################
# git-repos
##############################################
git_repos_to_clone:
  - repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{home_dir}}/.tmux/plugins/tpm"
    version: master
  - repo: "https://github.com/catppuccin/alacritty"
    dest: "{{home_dir}}/.config/alacritty/catppuccin"
    version: main
  - repo: "git@github.com:lordthorzonus/ble2mqtt-gateway"
    dest: "{{home_dir}}/projects/personal/ble2mqtt-gateway"
    version: main
  - repo: "git@github.com:lordthorzonus/homelab-provisioning"
    dest: "{{home_dir}}/projects/personal/homelab-provisioning"
    version: main
  - repo: "git@github.com:lordthorzonus/oura-api-exporter"
    dest: "{{home_dir}}/projects/personal/oura-api-exporter"
    version: main
  - repo: "git@github.com:lordthorzonus/php-dataloader"
    dest: "{{home_dir}}/projects/personal/php-dataloader"
    version: master
git_project_base_folders:
  - "{{home_dir}}/projects"
  - "{{home_dir}}/projects/personal"
  - "{{home_dir}}/projects/work"

##############################################
# nvm
##############################################
nvm_version: "0.39.5"
nvm_location: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
nvm_node_versions:
  - version: "v16"
  - version: "v18"
  - version: "v20"
nvm_default_node_version: "v16"
