import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = {family= "JetBrainsMono Nerd Font"}
size = 14.0

[window]
decorations = "None"
dynamic_padding = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
