import = [
  # "~/.config/alacritty/catpuccin/catppuccin-latte.toml"
  # "~/.config/alacritty/catpuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catpuccin/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "-c", "tmux a -t base || tmux new -s base"]

[font]
normal = {family= "ComicCodeLigatures Nerd Font", style = "Regular"}
size = 14.0

[window]
decorations = "None"
dynamic_padding = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
