---
- name: Install oh-my-zsh
  git:
    dest: "{{omz_home}}"
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    update: yes

- name: Install oh-my-zsh themes
  git:
    dest: "{{omz_home}}/custom/themes/{{item.name}}"
    repo: "{{item.git_repo}}"
  with_items: "{{omz_themes}}"

- name: Install oh-my-zsh plugins
  git:
    dest: "{{omz_home}}/custom/plugins/{{item.name}}"
    repo: "{{item.git_repo}}"
  with_items: "{{omz_plugins}}"