---
- name: Install neovim
  homebrew:
    name: nvim
    state: present
    update_homebrew: yes

- name: Install packer
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"